### ISSUE TITLE
Is it possible to get just the byte string for the filename in a single line?

### ISSUE THREAD

**Issue by NebularNerd** [pmqs/zipdetails#23]
Hi and thanks for this perl script, it might be the key to helping me with decoding Chinese zip files better.

Running the script with `-v` gives the following:
```
0000000 0000003 0000004 50 4B 03 04 LOCAL HEADER #1       04034B50 (67324752)
0000004 0000004 0000001 14          Extract Zip Spec      14 (20) '2.0'
0000005 0000005 0000001 00          Extract OS            00 (0) 'MS-DOS'
0000006 0000007 0000002 00 00       General Purpose Flag  0000 (0)
0000008 0000009 0000002 00 00       Compression Method    0000 (0) 'Stored'
000000A 000000D 0000004 0D A0 2B 52 Modification Time     522BA00D (1378590733) 'Mon Jan 11 20:00:26 2021'
000000E 0000011 0000004 00 00 00 00 CRC                   00000000 (0)
0000012 0000015 0000004 00 00 00 00 Compressed Size       00000000 (0)
0000016 0000019 0000004 00 00 00 00 Uncompressed Size     00000000 (0)
000001A 000001B 0000002 17 00       Filename Length       0017 (23)
000001C 000001D 0000002 00 00       Extra Length          0000 (0)
000001E 0000034 0000017 C9 CF CA D0 Filename              '╔¤╩ð╣½╦¥┤┤ð┬╩²¥¦═Ûı¹░µ/'
                        B9 AB CB BE
                        B4 B4 D0 C2
                        CA FD BE DD
                        CD EA D5 FB
                        B0 E6 2F

```

Which is handy as I can take the hex for the filename and decode it to find the correct charset using a decoder in python so `C9CFCAD0B9ABCBBEB4B4D0C2CAFDBEDDCDEAD5FBB0E62F` decode as a `big5` encoded name giving `奻庈鼠侗斐陔杅擂俇淕唳/`.

Is there a way to get the hex (or bytes) in a more simplified single line form? I'm sure I could somehow wrangle this output to give me a list of hex strings for all files but hopefully there is a better way 🙂

**Comment by pmqs** [comment]
Hey Andy (@NebularNerd)

sorry, but right now you will have to wrangle the bytes by parsing the tabular output from `zipdetails`. Creating a machine-readable output format is on my todo list (see https://github.com/pmqs/zipdetails?tab=readme-ov-file#jsonyml-output). I do have a use-case coming up _soon_ that will need this feature. The definition of "soon" is a movable feast.

If you know the zip files encodes filenames in `big5` you can get `zipdetails` to render the filename in the native encoding of your system like this.

```zipdetails -v --encoding big5 your.zip```

If you are running a modern system, where the charset of the system is likely UTF8, all should be fine. 

If you want to force the charset that `zipdetails` transcode the filename to,  include the `--output-encoding` option, like this

```zipdetails -v --encoding big5 --output-encoding utf8 your.zip```

Ping me if that doesn't work for you.

**Comment by NebularNerd** [comment]
Thanks, it's a bit annoying with non-western .zip files as they are a bit hit and miss. I've got a couple of Chinese zips where most of the files can by handled in python with `GBK` encoding but not all. I was trying to use [charset_normalizer](https://github.com/jawah/charset_normalizer) to automagically detect the correct codec but it fails for varying reasons trying to turn a string back into bytes or vice versa with encoding/decoding errors (partly to do with python's zipfile module not having a raw output either). My plan is to feed it the raw hex from your output and let charset figure out a valid encoding, then use that to decode the files with hopefully the full and correct name. It crazy enough that it should work...

I'll close this for now and have some fun figuring out how best to wrangle the output 🙂
