### ISSUE TITLE
t/files/0010-apache-commons-compress/input.bin is too large

### ISSUE THREAD

**Issue by eserte** [pmqs/zipdetails#5]
The huge input.bin (> 2GB) is part of the App-zipdetails-2.101 distribution --- I assume this is an accident and it should not be included?

**Comment by pmqs** [comment]
> The huge input.bin (> 2GB) is part of the App-zipdetails-2.101 distribution --- I assume this is an accident and it should not be included?

Correct - I'll sort it

**Comment by pmqs** [comment]
Fixed with https://github.com/pmqs/zipdetails/commit/bbc756c9810353d99ef69dbd3f737e7926ace1c2

Version 2.102 uploaded to CPAN
