### ISSUE TITLE
Fails if timezone is not UTC

### ISSUE THREAD

**Issue by eserte** [pmqs/zipdetails#9]
It seems that there are timezone-related test failures in App-zipdetails-2.105. E.g. with `TZ=Europe/Berlin` there are differences in the "Last Mod Time" output:
```
# 000A Last Mod Time         5277983D 'Tue Mar 23 18:01:58 2021'
```
vs
```
# 000A Last Mod Time         5277983D 'Tue Mar 23 19:01:58 2021'
```

**Comment by pmqs** [comment]
Thanks @eserte, I'm aware of those failures. 

I added a UTC option to this script specifically for use in the test harnesses so I wouldn't have these time zone test failures.

This weeks release was an attempt to fix the issue you are seeing, but the smokes are telling me that it hasn't worked. 

My code ultimately relies on `POSIX::mktime` to convert timestamps stored in  zip files into a Unix-style epoch offset. Looking at the smokes, the issue appears to be Windows only, so `mktime` must behave differently on Windows.


Need to research this some more.

**Comment by pmqs** [comment]
Windows `mktime` man page is [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mktime-mktime32-mktime64?view=msvc-170)
